### ISSUE TITLE
FTB-Sky-Adventures always crash

### ISSUE THREAD

**Issue by skap67490** [FTBTeam/FTB-Sky-Adventures#210] opened 2018-11-25 11:57 UTC
* **Modpack Version**:FTB SkyAdventure 1.2.1  

* **Issue**: My server Always crashdown and i don't know why , i just check the crashlog but don't understand anything 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0fecb843

* **Is it Repeatable?**: i Always reboot the server and crash all the time after few minutes

* **Mod/s Affected**: Don't know

* **Known Fix**: Don't know

**Comment by mross5013** [comment] 2018-11-30 23:32
I have been doing some research into this issue for my own Sky Adventures server and found that there was known crash issue for Minecraft 1.12.2 vanilla that gave the same log output as is in your crash log. The following is for that bug: [https://bugs.mojang.com/browse/MC-121586](https://bugs.mojang.com/browse/MC-121586) The bug was fixed in the 1.13.pre6 build (But that doesn't really help those of us running 1.12.2 versions of MC). It appears to be due to the thread hanging and not updating.
Hopefully the FTB and Forge teams will be able to address the issue soon.

**Comment by tfox83** [comment] 2019-01-09 19:32
Please try a fresh install, as we have not been able to reproduce this issue.

**Closed as completed by tfox83** 2019-01-09 19:32 UTC
