### ISSUE TITLE
Repeatable quest automation has to be added to make the endgame purchases reasonable

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Sky-Adventures#37] opened 2018-10-19 00:12 UTC
In its current state buying the set of creative items + alchemical tome for "completion" costs 75000 money. Your best three quests are UU matter at 100, draconic reactor cores at 300, and starfield creators at 50. The only way to complete quests currently is manually. 

Draconic reactor cores requirement of a chaos shard each makes them unviable, 250 chaos shards is far more expensive than the other options. In the current state of 1mB of UU to get the quest done they are quite cheap, and being only EMC and mana starfield creators also work out relatively easy to obtain so these both work.

This means depending on whether you take the tech or magic route you have to manually move your mouse back and forth across the screen to submit the item and then claim the reward either 750 or 1500 times. This turns buying any of the most expensive items a short period of crafting followed by dozens of minutes of just moving the mouse back and forth to click buttons repeatedly literally thousands of times over.

**Comment by kingofkyles** [comment] 2018-10-21 21:15
I 100% agree with this, I am using the enzyme quest to get money because it is completely automatable with 3 incubators and a few energy condensers once you get a decent amount of EMC and it is ridiculously repetitive to collect the money. If there was an option for multiple submissions of the same item or automation would be great, even if it was "expensive" to set up/craft.

**Comment by tfox83** [comment] 2018-10-22 20:31
This is being work on by the dev, once a process is in place it will be in released in a future update.

**Comment by tfox83** [comment] 2018-10-22 21:19
@LatvianModder  is working on this, ill label as 'in progress'

**Comment by LatvianModder** [comment] 2018-10-22 21:40
Na uh, there's a button: ![](https://ss.latmod.com/pc/2018-10-19_21.55.48.png)

(It's not very obvious though, I could change that to something else)

**Comment by Salnex** [comment] 2018-10-23 05:02
Well err.. That could have save me some time. Not saying I wrote a script to auto clock to hand in starfield creators one at a time but...

**Comment by tfox83** [comment] 2018-10-23 17:21
Ah perfect will close then, thanks

**Closed as completed by tfox83** 2018-10-23 17:21 UTC
Labels: fixed in dev

**Comment by N00byEdge** [comment] 2018-10-31 13:15
> (It's not very obvious though, I could change that to something else)

Did this change? I can no longer find that button in the GUI. Running FTBQuests 1.2.1.62 which seems to be the latest according to Jenkins.
![image](https://user-images.githubusercontent.com/2322546/47790306-1f111680-dd17-11e8-9276-09ca0e3d660c.png)
Clicking this button does nothing, but I have over 4 stacks of drums in my inventory.

And since you showed it on a non-repeatable quest, here is a screenshot from one where I have the items in my inventory, there is no such button:
![image](https://user-images.githubusercontent.com/2322546/47790362-41a32f80-dd17-11e8-8389-8c32d60f3df8.png)

**Comment by LatvianModder** [comment] 2018-10-31 16:20
Hm, a bug then

**Comment by N00byEdge** [comment] 2018-10-31 16:46
@LatvianModder Okay thanks for the verification. Should I open an issue on your repo with more info about my setup?

**Comment by LatvianModder** [comment] 2018-11-01 12:42
Woops, it's not a bug. I just haven't pushed that version from my git. There should be a version later today out fixing bugs and this too

**Comment by N00byEdge** [comment] 2018-11-01 12:56
Okay thanks. I thought I was crazy for not seeing the button and sitting here for 20 minutes turning in drums. I guess I will hold off on doing so until the update 👍

**Comment by maxxims** [comment] 2019-02-26 07:47
Was this fixed? Clicking that button does nothing.

**Comment by LatvianModder** [comment] 2019-02-26 20:11
The button was moved to bottom of that panel

**Comment by maxxims** [comment] 2019-02-26 20:59
But that button does only one item at a item, isn’t it supposed to consume entire stacks from players inventory?
