### ISSUE TITLE
My game keeps randomly freezing.

### ISSUE THREAD

**Issue by thefool101** [FTBTeam/FTB-Sky-Adventures#139] opened 2018-10-28 05:26 UTC
* **Modpack Version**: Latest Release

* **Issue**: 

Computer Specs: Core i7-3770k CPU
GPU: GTX 960
Memory: 8gb DDR3

* **Is it Repeatable?**:

**Comment by twsx** [comment] 2018-10-28 19:14
How much RAM have you assigned to the pack in the launcher?

This issue is usually caused by either not having enough RAM assigned (6GB should do the trick).
It can ALSO be caused by your CPU not keeping up. I was actually using the 3770k as well a while ago, and despite having more than enough RAM, I started to have problem with modded MC. Had to upgrade.

**Comment by thefool101** [comment] 2018-10-29 07:20
How do I dedicate more ram?

**Closed as completed** 2018-11-15 19:53 UTC
