### ISSUE TITLE
Nether Stars have EMC but can't be created.

### ISSUE THREAD

**Issue by raverdave-2k** [FTBTeam/FTB-Sky-Adventures#285] opened 2019-02-28 16:12 UTC
**Modpack Version**: 1.4.0-1.12.2

**Is it Repeatable?**: Yes

**Mod/s Affected**: Nether stars have an EMC value and so can be redeemed in the transmutation table / tablet, however they do not appear in the list of items that be taken back out.

I know you have the pack configured so not all items can be obtained via ProjectE so not 100% sure if this is an issue or intentional, however the fact that they still have an EMC value makes me unsure enough to warrant raising. 

After initially experiencing the problem on the included verion of ProjectE (1.3.2) I tried to updating to the last version (1.4.0) in case it was a bug with the mod rather than the pack but still happening in that version as well.

EDIT: The same thing just happened with the End Crystal, earned the EMC from it, got the Learned message but not found when searching. However tried with a random item (Diamond Hoe) and that worked as normal.

**Comment by raverdave-2k** [comment] 2019-03-06 16:00
Ok, now I'm almost certain this is a bug as I've just encountered the same thing with Diamond Blocks and as  I can pull individual diamonds out all day I can see no purpose why blocks of them would be disabled.

**Comment by Dahu88** [comment] 2019-03-07 09:45
You can obtain a nether star in the patience lootbag. A bag opener is handy for this one ;)

**Comment by cookta2012** [comment] 2019-03-11 08:30
It could be ProjectE causing a ghosting in the wheel of the table. Try to unlearn the items that are being a pain and then relearn them.

**Comment by Dahu88** [comment] 2019-03-11 09:08
There's also a strange behavior when you leave an item in the center

**Comment by cookta2012** [comment] 2019-03-11 11:02
Duplicate of #205

**Comment by cookta2012** [comment] 2019-03-12 23:04
See sinkillerj/ProjectE#1642.

**Comment by raverdave-2k** [comment] 2019-03-12 23:36
Thanks all for the comments, unlearning and relearning the individual items did not seem to solve the prolem so I ended up using the ProjectE command to unlearn everything and then used a Tomb of Knowledge, all the items I'd previously had issues with worked fine.

Following Dahu's comment I tried placing an item in the center of the wheel (I hadn't previously even released that was something that could be done) and that seemed to recreate the original problem I was having and removing it solved it again so I guess at some point I must have dropped something in that slot without even realising.

**Closed as completed** 2019-03-12 23:37 UTC
